
---
- hosts: kube_control_plane
  become: yes

  tasks:
    - name: Setup kubeconfig for user
      shell: |
        mkdir -p /home/vagrant/.kube
        cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        chown vagrant:vagrant /home/vagrant/.kube/config

    - name: Add serve alias for foo user
      ansible.builtin.lineinfile:
        path: /home/vagrant/.bashrc
        line: alias k=kubectl
        owner: vagrant
        regexp: '^alias serve=kubectl$'
        state: present
        insertafter: EOF
        create: yes
    
    - name: Install required packages
      apt:
        pkg:
          - bash-completion
        state: latest

    - name: add bash completion for kubectl
      become: true
      become_user: vagrant
      shell: |
        echo "source <(kubectl completion bash)" >> ~/.bashrc
