
---
- hosts: [localhost, all]
  connection: local
  become: yes

  tasks:
    - name: print host_vars
      debug:
        # variable nodes passed from Vagrantfile
        var: nodes

    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install required packages
      apt:
        pkg:
          - sshpass
          - git
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest

    - name: clone kuber-setup repo
      git:
        repo: https://github.com/terenty-rezman/kuber-setup.git
        dest: /home/vagrant/kuber-setup
        clone: yes
        update: yes

    - name: create inventory.ini for kubespray
      template:
        src: /home/vagrant/kuber-setup/master/kubespray/inventory.j2
        dest: /home/vagrant/kubespray/inventory/inventory.ini

    - name: create hosts
      template:
        src: /home/vagrant/kuber-setup/master/etc/hosts.j2
        dest: /etc/hosts

    - name: play ansible playbook on nodes to prepare them
      become: true
      become_user: vagrant
      shell: |
        ansible-playbook -i /home/vagrant/kubespray/inventory/inventory.ini --become prepare_nodes.yaml 
      args:
        chdir: /home/vagrant/kuber-setup/vagrant_dynamic

    - name: print info
      ansible.builtin.debug:
        msg: |
          kubespray is installed next from master vm to nodes vms
          to see ansible logs please use:
          vagrant ssh master -c "tail -f /tmp/kubespray.log"
      when: ansible_default_ipv4.gateway is defined

    - name: install kubespray
      become: true
      become_user: vagrant
      shell: |
        ansible-playbook -i inventory/inventory.ini --become cluster.yml 2>&1 | tee /tmp/kubespray.log
      args:
        chdir: /home/vagrant/kubespray

    - name: postinstall actions for control nodes
      become: true
      become_user: vagrant
      shell: |
        ansible-playbook -i /home/vagrant/kubespray/inventory/inventory.ini --become control_nodes_postinstall.yaml 
      args:
        chdir: /home/vagrant/kuber-setup/vagrant_dynamic
