---
- name: prepare hosts
  hosts: all
  become: yes

  tasks:
  - name: check if swap is on
    shell: swapon
    register: swapon_output


  - name: disable swap if enabler
    shell: swapoff -a
    when: swapon_output.stdout != ""


  - name: disable swap if fstab
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
