
---
- hosts: [localhost, all]
  connection: local
  become: yes
  roles: 
    - kwoodson.yedit

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install required packages
      apt:
        pkg:
          - sshpass
          - git
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Install docker compose
      apt:
        name: docker-compose-plugin
        state: latest

    - name: adding existing user 'vagrant' to group sudo
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: check if repo already cloned
      stat:
        path: /home/vagrant/kuber-setup
      register: already_cloned

    - name: clone kuber-setup repo
      git:
        repo: https://github.com/terenty-rezman/kuber-setup.git
        dest: /home/vagrant/kuber-setup
        clone: yes
        update: yes
      when: not already_cloned.stat.exists

    - name: deploy isc dhcp
      shell: |
        docker compose up -d
      args:
       chdir: /home/vagrant/kuber-setup/master/dhcp

    - name: pull dns bind image
      shell: |
        docker compose pull
      args:
       chdir: /home/vagrant/kuber-setup/master/dns_bind

    # https://tekanaid.com/posts/create-a-pihole-docker-ad-blocker-with-ansible-and-terraform
    - name: Disable Stub Resolver
      replace:
        path: /etc/systemd/resolved.conf
        regexp: '#*DNSStubListener=yes'
        replace: 'DNSStubListener=no'

    - name: Restart systemd-resolved
      systemd:
        state: restarted
        name: systemd-resolved
        daemon_reload: yes

    - name: deploy dns bind 
      shell: |
        docker compose up -d
      args:
       chdir: /home/vagrant/kuber-setup/master/dns_bind

    - name: custom resolv.conf
      shell: |
        rm /etc/resolv.conf
        ln -s /home/vagrant/kuber-setup/master/etc/resolv.conf /etc/resolv.conf

    # ansible-galaxy install kwoodson.yedit
    # https://github.com/kwoodson/ansible-role-yedit
    #- name: add search domain to netplan config
    #  yedit:
    #    src: /etc/netplan/01-netcfg.yaml
    #    key: network.ethernets.eth0.nameservers.search
    #    value: [kuber.home]

    #- name: apply netplan
      #shell: sudo netplan apply

    - name: copy kubespray inventory.ini
      ansible.builtin.copy:
        src: /home/vagrant/kuber-setup/master/kubespray/inventory.ini
        dest: /home/vagrant/kubespray/inventory/inventory.ini

          #- name: install kubespray
          #become: true
          #become_user: vagrant
          #shell: |
          #ansible-playbook -i inventory/inventory.ini --become cluster.yml &>1 | tee /tmp/kuberspray.log
          #args:
          #chdir: /home/vagrant/kubespray
