# -*- mode: ruby -*-
# vi: set ft=ruby :

# clone kubespray and install ansible for its requirements
$script = <<-SCRIPT
echo installing pip
sudo apt update
yes | sudo apt install pip
echo installing kubespray
cd 
git clone https://github.com/kubernetes-sigs/kubespray.git
cd kubespray
pip install -r requirements.txt
export PATH=/home/vagrant/.local/bin:$PATH
mkdir -p /home/vagrant/.ansible/roles
cd /home/vagrant/.ansible/roles
ansible-galaxy install kwoodson.yedit
SCRIPT


Vagrant.configure("2") do |config|

  config.vm.define "control1" do |control1|
    control1.vm.box = "generic/ubuntu2004"
    control1.disksize.size = "20GB"

    control1.vm.hostname = "control1"
    control1.vm.network "private_network", type: "dhcp", virtualbox__intnet: "kuber_internal",
      mac: "08002721ee3f"

    control1.vm.provider :virtualbox do |v, override|
      v.name = "control1"
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.define "worker1" do |worker|
    worker.vm.box = "generic/ubuntu2004"
    worker.disksize.size = "20GB"

    worker.vm.hostname = "worker1"
    worker.vm.network "private_network", type: "dhcp", virtualbox__intnet: "kuber_internal",
      mac: "080027afeffa"

    worker.vm.provider :virtualbox do |v, override|
      v.name = "worker1"
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.define "master" do |master|
    master.vm.box = "generic/ubuntu2004"
    master.disksize.size = "20GB"

    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.177.1", virtualbox__intnet: "kuber_internal"

    master.vm.provider :virtualbox do |v, override|
      v.name = "master"
      v.memory = 1024
      v.cpus = 1
    end

    master.vm.synced_folder ".", "/vagrant", SharedFoldersEnableSymlinksCreate: false

    master.vm.provision "shell", inline: $script, privileged: false

    master.vm.provision "ansible_local" do |ansible|
      ansible.install = false
      ansible.playbook = "prepare_master.yaml"
    end
  end

end
